# Generated by Django 4.2.1 on 2023-05-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
