# Generated by Django 4.2.1 on 2023-05-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0003_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
