# Generated by Django 4.2.1 on 2023-05-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0007_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
