# Generated by Django 4.2.1 on 2023-05-17 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0010_delete_user_account_date_account_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 0, 0, 26, 279837, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 17, 0, 0, 26, 279837, tzinfo=datetime.timezone.utc))),
                ('result', models.IntegerField(default=-1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retinoscope.account')),
            ],
        ),
    ]
