# Generated by Django 4.2.1 on 2023-06-13 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0012_remove_account_date_remove_account_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 13, 9, 11, 923804, tzinfo=datetime.timezone.utc)),
        ),
    ]
