# Generated by Django 4.2.1 on 2023-06-13 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinoscope', '0014_account_img_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 13, 16, 10, 349709, tzinfo=datetime.timezone.utc)),
        ),
    ]
